# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: sugarmint
  pool: 5
  username: sugar
  password: sugarchallenged
  host: localhost
  port: 3306

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: sugarmint
  pool: 5
  username: sugar
  password: sugarchallenged
  host: localhost
  port: 3306

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: sugarmint_prod
  pool: 5
  username: sugar
  password: sugarchallenged
  host: localhost
  port: 3306

