# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: <%= ENV["SUGAR_DB"] %>
  pool: 5
  username: <%= ENV["SUGAR_DB_USER"] %>
  password: <%= ENV["SUGAR_DB_PASSWORD"] %>
  host: localhost
  port: 3306

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: <%= ENV["SUGAR_DB"] %>
  pool: 5
  username: <%= ENV["SUGAR_DB_USER"] %>
  password: <%= ENV["SUGAR_DB_PASSWORD"] %>
  host: localhost
  port: 3306

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: <%= ENV["SUGAR_DB"] %>
  pool: 5
  username: <%= ENV["SUGAR_DB_USER"] %>
  password: <%= ENV["SUGAR_DB_PASSWORD"] %>
  host: localhost
  port: 3306

